// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIProducto.Data;

#nullable disable

namespace WebAPIProducto.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIProducto.Models.Producto", b =>
                {
                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("highDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("nameProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idProduct");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("WebAPIProducto.Models.ProvidersProduct", b =>
                {
                    b.Property<int>("idProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProvider"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("priceProduct")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idProvider");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("WebAPIProducto.Models.Producto", b =>
                {
                    b.HasOne("WebAPIProducto.Models.ProvidersProduct", "ProvidersProduct")
                        .WithMany()
                        .HasForeignKey("idProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvidersProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
